crud_minsa/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('paciente.urls')),
]

paciente/urls.py
from django.contrib import admin
from django.urls import path
from .models import Paciente
from .views import PacienteListView, PacienteCreateView, PacienteUpdateView, PacienteDeleteView

urlpatterns = [
    path('paciente', PacienteListView.as_view(), name='listar_paciente'),
    path('ingresar_paciente', PacienteCreateView. as_view(), name='ingresar_paciente'),
    path('editar_paciente/<int:pk>', PacienteUpdateView.as_view(), name='editar_paciente'),
    path('eliminar_paciente/<int:pk>', PacienteDeleteView.as_view(), name='eliminar_paciente'),
]

paciente/models.py
from django.db import models
from .constans import TIPDOC
from datetime import datetime
from django.conf import settings
from dateutil.relativedelta import relativedelta
from django.core.validators import MinLengthValidator


class Paciente(models.Model):
    tipo_documento = models.CharField('TIPO DE DOCUMENTO', max_length=1, choices=TIPDOC, blank=False, null=False, default=1)
    numero_documento = models.CharField('NUMERO DE DOCUMENTO', max_length=15, validators=[
                                        MinLengthValidator(8)], blank=False, null=True)
    nombres = models.CharField('NOMBRES', max_length=120, blank=True, null=True)
    apellido_paterno = models.CharField('APELLIDO PATERNO', max_length=90, blank=True, null=True)
    apellido_materno=models.CharField('APELLIDO MATERNO', max_length=90, blank=True, null=True)
    fecha_nacimiento = models.DateField('FECHA DE NACIMIENTO', blank=False, null=True)

    class Meta:
        unique_together = ('tipo_documento', 'numero_documento')

    def __str__(self):
        return self.nombre_completo

    @property
    def nombre_completo(self):
        return '{nombres} {a_paterno} {a_materno}'.format(
            nombres=self.nombres or '',
            a_paterno=self.apellido_paterno or '',
            a_materno=self.apellido_materno or ''
        )

    @property
    def edad(self):
        if not self.fecha_nacimiento:
            return ''
        edad1 = relativedelta(datetime.now().date(), self.fecha_nacimiento)
        if edad1.years < 1:
            if edad1.months <= 1:
                res = '{month} meses {day} días'.format(month=edad1.months, day=edad1.days)
            else:
                res = '{month} meses {day} días'.format(month=edad1.months, day=edad1.days)
        else:
            res = '{year} años, {month} meses {day} días'.format(year=edad1.years, month=edad1.months, day=edad1.days)

        return res

   # @classmethod
    #def crear_paciente(cls,tipo_documento, num_documento):

paciente/forms.py
from django import forms
from paciente.constans import TIPDOC
from .models import Paciente


class BuscarPacienteForm(forms.Form):
    tipo_documento = forms.ChoiceField(label='TIPO DE DOCUMENTO', choices=TIPDOC, initial='1', required=False,
                                       widget=forms.Select(attrs={'class': 'form-control', 'style': 'height:32px;'}))
    numero_documento = forms.CharField(label='NUMERO DE DOCUMENTO', max_length=15, min_length=8,
                                       widget=forms.TextInput(attrs={
                                           'placeholder': 'Ingrese el numero de documento a buscar'}), required=False)


class PacienteForm(forms.ModelForm):
    edad = forms.CharField(label='EDAD', widget=forms.TextInput(attrs={'readonly': 'True', 'id': 'edad'}))
    class Meta:
        model = Paciente
        unique_together = ('tipo_documento', 'numero_documento')
        # fields ="__all__"
        fields = ('tipo_documento', 'numero_documento', 'nombres', 'apellido_paterno',
                  'apellido_materno', 'fecha_nacimiento')
        widgets = {
            'tipo_documento': forms.Select(attrs={'class': 'form-control', 'style': 'height:34px;'}),
            'numero_documento': forms.TextInput(attrs={'class': 'form-control'}),
            'nombres': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_paterno': forms.TextInput(attrs={'class': 'form-control'}),
            'apellido_materno': forms.TextInput(attrs={'class': 'form-control'}),
            'fecha_nacimiento': forms.DateInput(attrs={'placeholder': 'dd-MM-yyyy', 'class': 'form-control'}),

        }

paciente/views.py
from django.shortcuts import render
from django.views.generic import ListView, FormView, CreateView, UpdateView, DeleteView
from .models import Paciente
from .forms import BuscarPacienteForm, PacienteForm
from django.forms.forms import NON_FIELD_ERRORS
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse


# Create your views here.


class PacienteListView(ListView, FormView):
    template_name = 'listar_paciente.html'
    model = Paciente
    context_object_name = 'pacientes'
    form_class = BuscarPacienteForm
    form = BuscarPacienteForm

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        pacientes = []
        form.is_valid()
        encontro=0
        tipo_documento = form.cleaned_data.get('tipo_documento')
        numero_documento = form.cleaned_data.get('numero_documento')
        try:
            paciente = Paciente.objects.get(tipo_documento=tipo_documento, numero_documento=numero_documento)
            encontro=1
        except:
                paciente=''
        return render(request, 'listar_paciente.html', {'form': form, 'paciente': paciente, 'encontro':encontro})
        #return self.render_to_response(self.get_context_data().update({'form': form, 'paciente': paciente, 'encontro':encontro}))


class PacienteCreateView(CreateView):
    model = Paciente
    template_name = 'ingresar_paciente.html'
    form_class = PacienteForm
    form = PacienteForm
    success_url = reverse_lazy('listar_paciente')

   # def clean(self):
    #    cleaned_data = super(Paciente, self).clean()
     #   tipo_documento = cleaned_data.get('tipo_documento')
      #  numero_documento = cleaned_data.get('numero_documento')
       # paciente = Paciente.objects.get(tipo_documento=tipo_documento,numero_documento=numero_documento)
        #raise paciente.ValidationError(
         #       'La cantidad no es correcta'
          #  )


class PacienteUpdateView(UpdateView):
    template_name = 'ingresar_paciente.html'
    model = Paciente
    form_class = PacienteForm
    success_url = reverse_lazy('listar_paciente')


class PacienteDeleteView(DeleteView):
    template_name = 'eliminar_paciente.html'
    model = Paciente
    success_url = reverse_lazy('listar_paciente')

paciente/templates/base.html

<!DOCTYPE html>
{% load staticfiles %}
    <html>
        <head>
            <meta charset="utf-8">
            <meta http-equiv="Content-Type" content="text/html; charset=gb18030">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

            <title>Ingresar Paciente</title>
            <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
            <script src="{% static 'js/js_paciente.js' %}"></script>
            <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
            <script src="{% static 'js/jquery-ui.js' %}"></script>
            <script src="{% static 'js/jquery-1.9.1.min.js' %}"></script>
 <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
            <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>

        </head>
        <body>

            <div class="content container">
                <div class="row">
                    <div class="col-md-8">
                        {% block content %}
                        {% endblock %}
                    </div>
                </div>
            </div>
        </div>
    </body>
</html>

paciente/templates/eliminar_paciente.html
{% extends 'base.html' %}
{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>¿Desea eliminar el registro de:  {{ paciente.nombres}} {{ paciente.apellido_paterno}} {{ paciente.apellido_materno}}</h3>
    <button class="btn btn-danger"  type="submit">Sí Eliminar</button>
    <a class="btn btn-default" href="../paciente">Cancelar</a>


</form>

{% endblock content %}

paciente/templates/ingresar_paciente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

     <script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>
    <link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
<script>
$(document).ready(function() {
//$(".alert").hide();
fec1=$("#id_fecha_nacimiento").val();
$("#malertf").show();$("#malertf").delay(3200).fadeOut(10);
 $("#edad").val(calculaedad1(fec1));
$("#id_fecha_nacimiento").datepicker({format: 'dd/mm/yyyy (D)',language: 'es'}).on("change", function(e) {
fec1=$("#id_fecha_nacimiento").val();
 $("#edad").val(calculaedad1(fec1));
});

$("#id_fecha_nacimiento").blur(function() {
fec1=$("#id_fecha_nacimiento").val();
 $("#edad").val(calculaedad1(fec1));
 });

	});
</script>


<br>
  <div class="p-3 container border rounded bg-white shadow-sm" style="box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.10);">
 <div class="p-3"> <h6><font class="text-info">INGRESA Y/O EDITA INFORMACION DE PACIENTE</font></h6></div>
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}
      <div class="alert alert-danger" role="alert" id="malertf">
<strong>Error!</strong>
          {{ error }}
</div>
      {% endfor %}
    {% endif %}



        <form method="post">
    {% csrf_token %}
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.tipo_documento|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.numero_documento|as_crispy_field }}
      </div>
         <div class="form-group col-md-3 mb-0">
        {{ form.nombres|as_crispy_field }}
       </div>
        <div class="form-group col-md-3 mb-3">
        {{ form.apellido_paterno|as_crispy_field }}
      </div>
    </div>
    <div class="form-row">
      <div class="form-group col-md-3 mb-0">
        {{ form.apellido_materno|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-0">
        {{ form.fecha_nacimiento|as_crispy_field }}
      </div>
      <div class="form-group col-md-3 mb-3">
        {{ form.edad|as_crispy_field }}
      </div>
    </div>
   <button type="submit"  class="btn btn-info" onclick="" id="guardar" value="GUARDAR"><span class="fas fa-save"></span> GUARDAR</button>
            {% if enc1 > 0 %}
            <div id="msg1" style="display:none;visibility:hidden;">{{enc1}}</div>
            {% endif %}
  </form>



       <div><br><br></div>
    <div class="row container ">
        <div class="col-sm ">

   </div>
    </div>

<div><br></div>
     <div class="row container ">

     <div class="col-sm " id="mostrarb">
     <input type="hidden"  id="med">

     </div>

    </div>


  </form>

</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
        <input type="hidden" class="form-control" id="idpersona" placeholder="">
      </div>
    </div>
  </div>
</div>


{% endblock %}

paciente/templates/listar_paciente.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}


 <div class="p-1 container border rounded bg-white shadow-sm" style="box-shadow: 0 2px 3px 0 rgba(0, 0, 0, 0.2), 0 3px 10px 0 rgba(0, 0, 0, 0.10);">
 <div class="p-3"> <h6><font class="text-info">BUSCAR PACIENTE</font></h6></div>

<form class="form" method="POST" id="id_form">{% csrf_token %}

      <div class="alert alert-danger" role="alert" id="malertv">
<strong>Error!</strong> No se encontraron resultados
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>

    <br>
    <form method="post" action="" class="form">
{% csrf_token %}
        <div class="container">
      <div class="row">
        <div class="col-sm">
             {{ form.tipo_documento|as_crispy_field}}
        </div>
        <div class="col-sm">
            {{ form.numero_documento|as_crispy_field}
        </div>
        <div class="col-sm">
            <label class="control-label small" ><i class="fas fa-briefcase"></i><strong>&nbsp;</strong></label>
            <div></div>
            <button type="submit"  class="btn btn-info" onclick="" id="guardar" value="GUARDAR"><span class="fas fa-save"></span> BUSCAR</button>
               <a class="btn btn-info" href="ingresar_paciente">CREAR PACIENTE</a>
        </div>
      </div>
        </div>
    </form>

<br>
<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Tipo de documento</th>
      <th scope="col">Numero de documento</th>
      <th scope="col">Fecha de Nacimiento</th>
      <th scope="col">Edad</th>
      <th scope="col">Nombres y Apellidos</th>
      <th scope="col">Gestionar Paciente</th>
    </tr>
  </thead>
        {% if encontro < 1 %}
                    <div id="msg1" style="display:none;visibility:hidden;">{{encontro}}</div>
        {% endif %}
        {% if paciente.id %}
    <tr>

                   <td> <span class="menu-title">{{ paciente.get_tipo_documento_display }}</span></td>
                   <td> <span class="menu-title">{{ paciente.numero_documento }}</span></td>
                   <td> <span class="menu-title">{{ paciente.fecha_nacimiento }}</span></td>
                   <td> <span class="menu-title">{{ paciente.edad }}</span></td>
                   <td> <span class="menu-title">{{ paciente.nombre_completo }}</span></td>
        <td>
                 <a class="btn btn-default" href="editar_paciente/{{ paciente.id }}"><span class="glyphicon glyphicon-pencil">Editar</span></a>
                 <a class="btn btn-default" href="eliminar_paciente/{{ paciente.id }}"><span class="glyphicon glyphicon-trash">Eliminar</span></a>
                </td>

    </tr>
        {% endif %}
            	<tbody>
                   {% for value in object_list %}
            <tr>
                <td> <span class="menu-title">{{ value.get_tipo_documento_display }}</span></td>
                <td> <span class="menu-title">{{ value.numero_documento }}</span></td>
                <td> <span class="menu-title">{{ value.fecha_nacimiento }}</span></td>
                <td> <span class="menu-title">{{ value.edad }}</span></td>
                <td> <span class="menu-title">{{ value.nombre_completo }}</span></td>
                <td>
                 <a class="btn btn-default" href="editar_paciente/{{ value.id }}"><span class="glyphicon glyphicon-pencil">Editar</span></a>
                 <a class="btn btn-default" href="eliminar_paciente/{{ value.id }}"><span class="glyphicon glyphicon-trash">Eliminar</span></a>
                </td>
            </tr>
             {% endfor %}
            </tbody>

</table>

<script>

$(document).ready(function() {
$(".alert").hide();
if($("#msg1").html()==0){$("#malertv").show();$("#malertv").delay(3200).fadeOut(10);}

	});


</script>


{% endblock %}